[package]
name = "cairo_doc_gen"
version = "0.1.0"
description = "A documentation generator for Cairo smart contracts."
authors = ["Your Name"]
edition = "2024_07"

[dependencies]
cairo_doc_gen = { path = "../cairo_doc_gen" }
